name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y libncurses5-dev libncursesw5-dev
      
    - name: Run autoreconf
      run: autoreconf -i
      
    - name: configure
      run: ./configure

    - name: Build
      run: make

    - name: Test binary
      run: ./cmatrix-pipes -V
